/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Analysis.Semigroups.Generator.Closed
public import TauCeti.LinearAlgebra.LinearPMap.RestrictScalars
public import Mathlib.Analysis.Complex.Basic
import TauCeti.Analysis.Semigroups.Generator.Similarity
import TauCeti.Analysis.Semigroups.Generator.Uniqueness

/-!
# Complex-linear operators from real strongly continuous semigroups

A strongly continuous semigroup in Tau Ceti acts by real continuous linear maps, including on a
complex Banach space regarded as a real Banach space. This file records the additional hypothesis
that each operator commutes with complex scalar multiplication and bundles each operator as a
complex continuous linear map. It does not introduce a parallel complex semigroup.

## Main definitions and results

* `StronglyContinuousSemigroup.IsComplexLinear`: every semigroup operator is complex linear.
* `StronglyContinuousSemigroup.complexOperator`: the operator at a fixed time, bundled over `ℂ`.
* `StronglyContinuousSemigroup.complexOperator_apply`: the complex bundle has the same action.
* `StronglyContinuousSemigroup.complexOperator_restrictScalars`: restriction to `ℝ` recovers the
  original semigroup operator.
* `StronglyContinuousSemigroup.complexDomain`: the generator domain as a complex submodule.
* `StronglyContinuousSemigroup.mem_complexDomain_iff`: membership agrees with the real domain.
* `StronglyContinuousSemigroup.complexGenerator`: the real generator bundled as a complex
  `LinearPMap` on the same domain.
* `StronglyContinuousSemigroup.dense_complexDomain`: the complex generator domain is dense.
* `StronglyContinuousSemigroup.isClosed_complexGenerator`: the complex generator is closed.
* `StronglyContinuousSemigroup.complexGenerator_restrictScalars`: restricting the complex
  generator to real scalars recovers the real generator.
* `StronglyContinuousSemigroup.isComplexLinear_of_I_smul`: commuting with multiplication by `i`
  suffices for complex linearity.
* `StronglyContinuousSemigroup.mem_domain_iff_of_generator_eq_restrictScalars`: the generator
  domain is the domain of the complex-linear partial map the generator restricts.
* `StronglyContinuousSemigroup.isComplexLinear_of_generator_eq_restrictScalars`: a semigroup
  whose generator is the real restriction of a complex-linear partial map is complex linear, by
  conjugating with `i` and using uniqueness of the semigroup generated by an operator.
* `StronglyContinuousSemigroup.complexGenerator_eq_of_generator_eq_restrictScalars`: the
  complex generator of such a semigroup is that complex-linear partial map.
-/

public section

noncomputable section

open Filter
open scoped NNReal Topology

namespace TauCeti.Semigroups

namespace StronglyContinuousSemigroup

variable {X : Type*} [NormedAddCommGroup X] [NormedSpace ℂ X] [CompleteSpace X]

/-- A real C₀-semigroup on a complex normed space is complex linear when every operator commutes
with complex scalar multiplication. -/
@[expose] def IsComplexLinear (S : StronglyContinuousSemigroup X) : Prop :=
  ∀ (t : ℝ≥0) (z : ℂ) (x : X), S t (z • x) = z • S t x

/-- A complex-linear semigroup operator, bundled as a complex continuous linear map. -/
def complexOperator (S : StronglyContinuousSemigroup X) (hS : S.IsComplexLinear)
    (t : ℝ≥0) :
    X →L[ℂ] X where
  toFun := S t
  map_add' := (S t).map_add
  map_smul' := hS t
  cont := (S t).continuous

omit [CompleteSpace X] in
/-- The complex operator has the same pointwise action as the underlying real operator. -/
@[simp]
theorem complexOperator_apply (S : StronglyContinuousSemigroup X) (hS : S.IsComplexLinear)
    (t : ℝ≥0) (x : X) : S.complexOperator hS t x = S t x :=
  (rfl)

omit [CompleteSpace X] in
/-- Restricting the complex operator to real scalars recovers the semigroup operator. -/
@[simp]
theorem complexOperator_restrictScalars (S : StronglyContinuousSemigroup X)
    (hS : S.IsComplexLinear) (t : ℝ≥0) :
    (S.complexOperator hS t).restrictScalars ℝ = S t :=
  ContinuousLinearMap.ext fun x => S.complexOperator_apply hS t x

omit [CompleteSpace X] in
/-- The difference quotient of `z • x` is `z` times the difference quotient of `x`, so it converges
to `z • A x` for `x` in the generator domain. -/
private theorem tendsto_genQuot_smul (S : StronglyContinuousSemigroup X) (hS : S.IsComplexLinear)
    (x : S.domain) (z : ℂ) :
    Tendsto (fun t : ℝ => (1 / t) • (S.realOperator t (z • (x : X)) - z • (x : X)))
      (𝓝[>] (0 : ℝ))
      (𝓝 (z • S.generator ⟨(x : X), by rw [S.generator_domain]; exact x.property⟩)) := by
  refine ((S.generator_tendsto x).const_smul z).congr' (Eventually.of_forall fun t => ?_)
  dsimp only
  rw [S.realOperator_def, hS]
  simp only [smul_sub, smul_comm (1 / t) z]

/-- The generator domain of a complex-linear semigroup, as a complex submodule. -/
def complexDomain (S : StronglyContinuousSemigroup X) (hS : S.IsComplexLinear) :
    Submodule ℂ X where
  carrier := S.domain
  zero_mem' := S.domain.zero_mem
  add_mem' := S.domain.add_mem
  smul_mem' z x hx :=
    (S.mem_domain_iff_tendsto (z • x)).mpr ⟨_, tendsto_genQuot_smul S hS ⟨x, hx⟩ z⟩

omit [CompleteSpace X] in
/-- Membership in the complex generator domain is membership in the underlying real domain. -/
@[simp]
theorem mem_complexDomain_iff (S : StronglyContinuousSemigroup X) (hS : S.IsComplexLinear)
    (x : X) : x ∈ S.complexDomain hS ↔ x ∈ S.domain :=
  Iff.rfl

omit [CompleteSpace X] in
/-- The complex generator domain has the real generator domain as its underlying set. -/
@[simp]
theorem coe_complexDomain (S : StronglyContinuousSemigroup X) (hS : S.IsComplexLinear) :
    ((S.complexDomain hS : Submodule ℂ X) : Set X) = (S.domain : Set X) :=
  (rfl)

/-- The infinitesimal generator, bundled as a complex linear partial map. -/
noncomputable def complexGenerator (S : StronglyContinuousSemigroup X)
    (hS : S.IsComplexLinear) : X →ₗ.[ℂ] X where
  domain := S.complexDomain hS
  toFun :=
    { toFun := fun x => S.generator ⟨x, by
        rw [S.generator_domain]
        exact x.property⟩
      map_add' := fun x y =>
        S.generator.map_add ⟨(x : X), by rw [S.generator_domain]; exact x.property⟩
          ⟨(y : X), by rw [S.generator_domain]; exact y.property⟩
      map_smul' := fun z x =>
        S.generator_eq_of_tendsto
          ((S.mem_complexDomain_iff hS _).mp ((S.complexDomain hS).smul_mem z x.property))
          (tendsto_genQuot_smul S hS ⟨(x : X), x.property⟩ z) }

omit [CompleteSpace X] in
/-- The complex generator has the complex generator domain. -/
@[simp]
theorem complexGenerator_domain (S : StronglyContinuousSemigroup X)
    (hS : S.IsComplexLinear) : (S.complexGenerator hS).domain = S.complexDomain hS :=
  (rfl)

omit [CompleteSpace X] in
/-- The complex generator agrees pointwise with the underlying real generator. -/
@[simp]
theorem complexGenerator_apply (S : StronglyContinuousSemigroup X)
    (hS : S.IsComplexLinear) (x : (S.complexGenerator hS).domain) :
    S.complexGenerator hS x = S.generator ⟨(x : X), by
      rw [S.generator_domain]
      exact x.property⟩ :=
  (rfl)

/-- The domain of the complex generator is dense. -/
theorem dense_complexDomain (S : StronglyContinuousSemigroup X)
    (hS : S.IsComplexLinear) : Dense (S.complexDomain hS : Set X) := by
  rw [S.coe_complexDomain hS]
  exact S.dense_domain

/-- The complex generator is closed. -/
theorem isClosed_complexGenerator (S : StronglyContinuousSemigroup X)
    (hS : S.IsComplexLinear) : (S.complexGenerator hS).IsClosed := by
  rw [LinearPMap.IsClosed]
  have hgraph : ((S.complexGenerator hS).graph : Set (X × X)) =
      (S.generator.graph : Set (X × X)) := by
    ext p
    simp only [SetLike.mem_coe, LinearPMap.mem_graph_iff]
    constructor
    · rintro ⟨x, hx, hAx⟩
      refine ⟨⟨(x : X), ?_⟩, hx, ?_⟩
      · rw [S.generator_domain, ← S.mem_complexDomain_iff hS, ← S.complexGenerator_domain hS]
        exact x.property
      · simpa only [S.complexGenerator_apply hS x] using hAx
    · rintro ⟨x, hx, hAx⟩
      refine ⟨⟨(x : X), ?_⟩, hx, ?_⟩
      · rw [S.complexGenerator_domain hS, S.mem_complexDomain_iff hS, ← S.generator_domain]
        exact x.property
      · simpa only [S.complexGenerator_apply hS] using hAx
  rw [hgraph]
  exact S.isClosed_generator

omit [CompleteSpace X] in
/-- The real restriction of the complex generator is the real generator. -/
@[simp]
theorem complexGenerator_restrictScalars (S : StronglyContinuousSemigroup X)
    (hS : S.IsComplexLinear) : (S.complexGenerator hS).restrictScalars ℝ = S.generator := by
  refine LinearPMap.ext ?_ ?_
  · ext x
    rw [LinearPMap.mem_restrictScalars_domain ℝ, S.complexGenerator_domain hS,
      S.mem_complexDomain_iff hS, S.generator_domain]
  · intro x hx _
    rw [LinearPMap.restrictScalars_apply]
    exact S.complexGenerator_apply hS _

/-! ## Complex linearity from the generator -/

/-- Multiplication by `i` as a real continuous linear equivalence. -/
private def mulI : X ≃L[ℝ] X :=
  ContinuousLinearEquiv.smulLeft (Units.mk0 Complex.I Complex.I_ne_zero)

omit [CompleteSpace X] in
private theorem mulI_apply (x : X) : mulI x = Complex.I • x := rfl

omit [CompleteSpace X] in
private theorem mulI_symm_apply (x : X) : mulI.symm x = -Complex.I • x := by
  rw [ContinuousLinearEquiv.symm_apply_eq, mulI_apply, smul_smul, mul_neg, Complex.I_mul_I,
    neg_neg, one_smul]

omit [CompleteSpace X] in
/-- A real-linear semigroup commuting with multiplication by `i` is complex linear. -/
theorem isComplexLinear_of_I_smul (S : StronglyContinuousSemigroup X)
    (h : ∀ (t : ℝ≥0) (x : X), S t (Complex.I • x) = Complex.I • S t x) : S.IsComplexLinear := by
  intro t z x
  have hz : ∀ y : X, z • y = (z.re : ℝ) • y + (z.im : ℝ) • (Complex.I • y) := by
    intro y
    rw [RCLike.real_smul_eq_coe_smul (K := ℂ), RCLike.real_smul_eq_coe_smul (K := ℂ), smul_smul,
      ← add_smul]
    simp only [Complex.coe_algebraMap, Complex.re_add_im]
  rw [hz x, (S t).map_add, (S t).map_smul, (S t).map_smul, h, hz (S t x)]

omit [CompleteSpace X] in
/-- The generator domain of `S` is the domain of `A` when `S.generator = A.restrictScalars ℝ`. -/
theorem mem_domain_iff_of_generator_eq_restrictScalars
    (S : StronglyContinuousSemigroup X) {A : X →ₗ.[ℂ] X}
    (hA : S.generator = A.restrictScalars ℝ) {y : X} : y ∈ S.domain ↔ y ∈ A.domain := by
  rw [← S.generator_domain, hA, LinearPMap.mem_restrictScalars_domain ℝ]

omit [CompleteSpace X] in
/-- Conjugating by `i` preserves the generator domain when the generator is complex linear. -/
private theorem similar_mulI_generator_domain (S : StronglyContinuousSemigroup X)
    {A : X →ₗ.[ℂ] X} (hA : S.generator = A.restrictScalars ℝ) :
    (S.similar mulI).generator.domain = S.generator.domain := by
  ext y
  rw [(S.similar mulI).generator_domain, S.generator_domain, S.mem_similar_domain_iff,
    mulI_symm_apply, S.mem_domain_iff_of_generator_eq_restrictScalars hA,
    S.mem_domain_iff_of_generator_eq_restrictScalars hA]
  constructor
  · intro hy
    have := A.domain.smul_mem Complex.I hy
    rwa [smul_smul, mul_neg, Complex.I_mul_I, neg_neg, one_smul] at this
  · exact fun hy => A.domain.smul_mem _ hy

omit [CompleteSpace X] in
/-- Conjugating by `i` preserves the generator action when the generator is complex linear. -/
private theorem similar_mulI_generator_apply (S : StronglyContinuousSemigroup X)
    {A : X →ₗ.[ℂ] X} (hA : S.generator = A.restrictScalars ℝ) {y : X}
    (hy : y ∈ (S.similar mulI).generator.domain) (hy' : y ∈ S.generator.domain) :
    (S.similar mulI).generator ⟨y, hy⟩ = S.generator ⟨y, hy'⟩ := by
  rw [(S.similar mulI).generator_domain] at hy
  rw [S.similar_generator_apply mulI hy, mulI_apply]
  have hyA : y ∈ A.domain :=
    (S.mem_domain_iff_of_generator_eq_restrictScalars hA).mp
      (by rwa [S.generator_domain] at hy')
  have hyA' : mulI.symm y ∈ A.domain := by
    rw [mulI_symm_apply]
    exact A.domain.smul_mem _ hyA
  have key : ∀ (w : X) (hw : w ∈ S.generator.domain) (hwA : w ∈ A.domain),
      S.generator ⟨w, hw⟩ = A ⟨w, hwA⟩ := fun w hw hwA => by
    rw [@(LinearPMap.ext_iff.mp hA).2 w hw ((A.mem_restrictScalars_domain ℝ).mpr hwA),
      LinearPMap.restrictScalars_apply]
  have hmk : (⟨mulI.symm y, hyA'⟩ : A.domain) = (-Complex.I) • (⟨y, hyA⟩ : A.domain) :=
    Subtype.ext (by rw [Submodule.coe_smul]; exact mulI_symm_apply y)
  rw [key _ _ hyA', key y hy' hyA, hmk, A.map_smul, smul_smul, mul_neg, Complex.I_mul_I,
    neg_neg, one_smul]

/-- **Complex linearity is read off the generator.** A real C₀-semigroup on a complex Banach
space whose generator is the real restriction of a complex-linear partial map is complex linear. -/
theorem isComplexLinear_of_generator_eq_restrictScalars (S : StronglyContinuousSemigroup X)
    {A : X →ₗ.[ℂ] X} (hA : S.generator = A.restrictScalars ℝ) : S.IsComplexLinear := by
  have hS : S.similar mulI = S :=
    eq_of_generator_eq (LinearPMap.ext (S.similar_mulI_generator_domain hA)
      fun _ hy hy' => S.similar_mulI_generator_apply hA hy hy')
  refine S.isComplexLinear_of_I_smul fun t x => ?_
  have h := congrArg (fun T : StronglyContinuousSemigroup X => T t (Complex.I • x)) hS
  simp only [similar_apply, mulI_apply, mulI_symm_apply, smul_smul, neg_mul, Complex.I_mul_I,
    neg_neg, one_smul] at h
  exact h.symm

omit [CompleteSpace X] in
/-- The complex generator of a complex-linear semigroup whose real generator is the real
restriction of `A` is `A` itself. -/
theorem complexGenerator_eq_of_generator_eq_restrictScalars (S : StronglyContinuousSemigroup X)
    (hS : S.IsComplexLinear) {A : X →ₗ.[ℂ] X} (hA : S.generator = A.restrictScalars ℝ) :
    S.complexGenerator hS = A := by
  refine LinearPMap.ext ?_ ?_
  · ext x
    rw [S.complexGenerator_domain hS, S.mem_complexDomain_iff hS,
      S.mem_domain_iff_of_generator_eq_restrictScalars hA]
  · intro x hx hxA
    rw [S.complexGenerator_apply hS ⟨x, hx⟩,
      @(LinearPMap.ext_iff.mp hA).2 x _ ((A.mem_restrictScalars_domain ℝ).mpr hxA),
      LinearPMap.restrictScalars_apply]

end StronglyContinuousSemigroup

end TauCeti.Semigroups

end
