/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Analysis.Semigroups.Generator.OrbitDerivative
public import TauCeti.Analysis.Semigroups.GrowthBound
import Mathlib.Analysis.Calculus.Deriv.Shift
import Mathlib.Analysis.Calculus.MeanValue

/-!
# The generator determines the semigroup

Two strongly continuous semigroups on a real Banach space with the same infinitesimal generator
coincide. The proof is the classical interpolation argument: for `x` in the common generator
domain and a fixed time `t`, the orbit

`u ↦ S (t - u) (T u x)`

interpolates between `S t x` (at `u = 0`) and `T t x` (at `u = t`), and it is constant because
its right derivative vanishes: the derivative of the inner factor contributes the vector
`S (t - u) (A (T u x))`, and the derivative of the outer factor contributes its negative.

Differentiating the outer factor requires a two-sided derivative of a generator-domain orbit,
which is available at positive times through
`TauCeti.Semigroups.StronglyContinuousSemigroup.realOperator_hasDerivWithinAt_Ici`; both
contributions are recombined using the joint strong continuity
`TauCeti.Semigroups.StronglyContinuousSemigroup.tendsto_realOperator_apply` from
`TauCeti/Analysis/Semigroups/GrowthBound.lean`.

The concrete identifications this makes available are recorded with the semigroups they
identify: a semigroup with vanishing generator is the identity semigroup
(`TauCeti/Analysis/Semigroups/Identity.lean`), and a semigroup whose generator is a bounded
operator `A` is `t ↦ exp (t • A)` (`TauCeti/Analysis/Semigroups/BoundedGenerator/Basic.lean`).

## Main results

* `hasDerivWithinAt_realOperator_apply_realOperator_zero` (in the
  `TauCeti.Semigroups.StronglyContinuousSemigroup` namespace): a composite orbit
  `u ↦ S (f u) (T u x)` has vanishing right derivative when the generator contribution of `T`
  cancels the derivative of `u ↦ S (f u) (T s x)`.
* `realOperator_apply_realOperator_eq_of_hasDerivWithinAt_zero` (same namespace): a composite
  orbit with vanishing right derivative on `[0, t)` has value `S (f 0) x` at `t`.
* `TauCeti.Semigroups.StronglyContinuousSemigroup.realOperator_eq_of_generator_eq`: two
  semigroups with the same generator agree on the generator domain.
* `TauCeti.Semigroups.StronglyContinuousSemigroup.eq_of_generator_eq` and
  `TauCeti.Semigroups.StronglyContinuousSemigroup.generator_injective`: the generator determines
  the semigroup.
* `TauCeti.Semigroups.ContractionSemigroup.eq_of_generator_eq`: the contraction-semigroup form.

## References

* K.-J. Engel and R. Nagel, *One-Parameter Semigroups for Linear Evolution Equations*,
  Theorem II.1.4.
* A. Pazy, *Semigroups of Linear Operators and Applications to Partial Differential Equations*,
  Theorem 1.2.6.
-/

public section

noncomputable section

open Filter Set

open scoped Topology NNReal

namespace TauCeti.Semigroups

variable {X : Type*} [NormedAddCommGroup X] [NormedSpace ℝ X] [CompleteSpace X]

namespace StronglyContinuousSemigroup

/-! ## Uniqueness of the semigroup generated by an operator -/

/-- **The backwards orbit of a domain point.** Reading the orbit of `y ∈ D(A)` backwards from a
fixed time `t`, the derivative at `s < t` is the negative of the generator transported along the
remaining time `t - s`. -/
private theorem hasDerivAt_realOperator_sub {S : StronglyContinuousSemigroup X} {t s : ℝ}
    (hrpos : 0 < t - s) {y a : X} (hy : y ∈ S.generator.domain)
    (hSa : S.generator ⟨y, hy⟩ = a) :
    HasDerivAt (fun u : ℝ => S.realOperator (t - u) y) (-(S.realOperator (t - s) a)) s := by
  have hyS : y ∈ S.domain := by rwa [S.generator_domain] at hy
  have hpsi : HasDerivAt (fun u : ℝ => S.realOperator u y) (S.realOperator (t - s) a) (t - s) := by
    have h := S.realOperator_hasDerivWithinAt_Ici ⟨y, hyS⟩ hrpos.le
    rw [S.realOperator_generator_map hrpos.le ⟨y, hyS⟩] at h
    simp only [hSa] at h
    exact h.hasDerivAt (Ici_mem_nhds hrpos)
  exact HasDerivAt.comp_const_sub t s hpsi

/-- **The two contributions cancel.** Along a time reparametrisation `f`, right-continuous at `s`
and nonnegative near `s`, if the rebased generator quotient of `T` at `T s x` converges to `a` and
`u ↦ S (f u) (T s x)` has right derivative `-(S (f s) a)` at `s`, then the composite orbit
`u ↦ S (f u) (T u x)` has right derivative `0` at `s`: pushing the quotient through `S (f u)`
produces `S (f s) a`, cancelling the other derivative. -/
theorem hasDerivWithinAt_realOperator_apply_realOperator_zero
    (S T : StronglyContinuousSemigroup X) {f : ℝ → ℝ} {x a : X} {s : ℝ} (hs : 0 ≤ s)
    (hf : Tendsto f (𝓝[>] s) (𝓝 (f s))) (hf0 : ∀ᶠ u in 𝓝[>] s, 0 ≤ f u)
    (hquot : Tendsto (fun u : ℝ =>
      (u - s)⁻¹ • (T.realOperator (u - s) (T.realOperator s x) - T.realOperator s x))
      (𝓝[>] s) (𝓝 a))
    (hslope : HasDerivWithinAt (fun u : ℝ => S.realOperator (f u) (T.realOperator s x))
      (-(S.realOperator (f s) a)) (Set.Ici s) s) :
    HasDerivWithinAt (fun u : ℝ => S.realOperator (f u) (T.realOperator u x)) 0 (Set.Ici s) s := by
  have hfs : 0 ≤ f s := ge_of_tendsto hf hf0
  have hterm1 : Tendsto (fun u : ℝ => S.realOperator (f u)
      ((u - s)⁻¹ • (T.realOperator (u - s) (T.realOperator s x) - T.realOperator s x)))
      (𝓝[>] s) (𝓝 (S.realOperator (f s) a)) :=
    S.tendsto_realOperator_apply hf hf0 hfs hquot
  have h := T.hasDerivWithinAt_apply_realOperator_of_tendsto (fun u => S.realOperator (f u)) x hs
    hterm1 hslope
  rwa [add_neg_cancel] at h

/-- The interpolation `u ↦ S (t - u) (T u x)` between the two semigroups has vanishing right
derivative at every `u ∈ [0, t)`.

The two contributions cancel: differentiating `T u x` produces `S (t - u) (A (T u x))`, and
differentiating `S (t - u)` produces its negative, because the common generator `A` computes both
derivatives. -/
private theorem hasDerivWithinAt_interpolate {S T : StronglyContinuousSemigroup X}
    (hgen : S.generator = T.generator) {t : ℝ} {x : X} (hx : x ∈ T.domain) {s : ℝ}
    (hs0 : 0 ≤ s) (hst : s < t) :
    HasDerivWithinAt (fun u : ℝ => S.realOperator (t - u) (T.realOperator u x)) 0
      (Set.Ici s) s := by
  have hdom : S.domain = T.domain := by
    rw [← S.generator_domain, ← T.generator_domain, hgen]
  have hrpos : (0 : ℝ) < t - s := sub_pos.mpr hst
  set y : X := T.realOperator s x
  have hyT : y ∈ T.domain := T.realOperator_mem_domain hs0 hx
  have hyT' : y ∈ T.generator.domain := by rw [T.generator_domain]; exact hyT
  have hyS' : y ∈ S.generator.domain := by rw [S.generator_domain, hdom]; exact hyT
  set a : X := T.generator ⟨y, hyT'⟩
  have hSa : S.generator ⟨y, hyS'⟩ = a := @(LinearPMap.ext_iff.mp hgen).2 y hyS' hyT'
  -- The outer factor: the orbit of `y ∈ D(A)` read backwards from the fixed time `t`.
  have hrho : HasDerivAt (fun u : ℝ => S.realOperator (t - u) y)
      (-(S.realOperator (t - s) a)) s :=
    hasDerivAt_realOperator_sub hrpos hyS' hSa
  -- The inner factor: the defining difference quotient of the generator of `T` at `y`.
  have hquot : Tendsto (fun u : ℝ => (u - s)⁻¹ • (T.realOperator (u - s) y - y))
      (𝓝[>] s) (𝓝 a) := T.generator_tendsto_comp_sub_const ⟨y, hyT⟩ s
  have htime : Tendsto (fun u : ℝ => t - u) (𝓝[>] s) (𝓝 (t - s)) :=
    ((continuous_sub_left t).tendsto s).mono_left nhdsWithin_le_nhds
  exact S.hasDerivWithinAt_realOperator_apply_realOperator_zero T (f := fun u => t - u) hs0 htime
    ((htime.eventually_const_lt hrpos).mono fun _ h => h.le) hquot hrho.hasDerivWithinAt

/-- **A composite orbit with vanishing right derivative is constant.** If `u ↦ S (f u) (T u x)` has
right derivative `0` on `[0, t)`, with `f` continuous and nonnegative on `[0, t]`, then its value
at `t` is its value at `0`, namely `S (f 0) x`. -/
theorem realOperator_apply_realOperator_eq_of_hasDerivWithinAt_zero
    (S T : StronglyContinuousSemigroup X) {f : ℝ → ℝ} {x : X} {t : ℝ} (ht : 0 ≤ t)
    (hf : ContinuousOn f (Set.Icc 0 t)) (hf0 : ∀ u ∈ Set.Icc (0 : ℝ) t, 0 ≤ f u)
    (hderiv : ∀ u ∈ Set.Ico (0 : ℝ) t,
      HasDerivWithinAt (fun v : ℝ => S.realOperator (f v) (T.realOperator v x)) 0
        (Set.Ici u) u) :
    S.realOperator (f t) (T.realOperator t x) = S.realOperator (f 0) x := by
  have hcont : ContinuousOn (fun u : ℝ => S.realOperator (f u) (T.realOperator u x))
      (Set.Icc 0 t) :=
    S.continuousOn_realOperator_apply hf hf0
      ((T.realOperator_continuousOn_Ici x).mono fun u hu => hu.1)
  have heq := constant_of_has_deriv_right_zero hcont hderiv t (Set.right_mem_Icc.mpr ht)
  simpa only [T.realOperator_zero_apply] using heq

/-- Two strongly continuous semigroups with the same generator agree on the generator domain,
at every nonnegative time. -/
theorem realOperator_eq_of_generator_eq {S T : StronglyContinuousSemigroup X}
    (hgen : S.generator = T.generator) {t : ℝ} (ht : 0 ≤ t) {x : X} (hx : x ∈ T.domain) :
    S.realOperator t x = T.realOperator t x := by
  have h := S.realOperator_apply_realOperator_eq_of_hasDerivWithinAt_zero T (f := fun u => t - u)
    ht (continuous_sub_left t).continuousOn (fun u hu => sub_nonneg.mpr hu.2)
    fun _ hu => hasDerivWithinAt_interpolate hgen hx hu.1 hu.2
  simpa only [sub_self, sub_zero, S.realOperator_zero_apply] using h.symm

/-- **The generator determines the semigroup**: two strongly continuous semigroups on a real
Banach space with the same infinitesimal generator are equal ([EN] Thm. II.1.4). -/
theorem eq_of_generator_eq {S T : StronglyContinuousSemigroup X}
    (hgen : S.generator = T.generator) : S = T := by
  refine StronglyContinuousSemigroup.ext fun τ => ?_
  refine T.eq_of_eqOn_domain fun x hx => ?_
  simpa using realOperator_eq_of_generator_eq hgen τ.coe_nonneg hx

/-- The infinitesimal generator is injective on strongly continuous semigroups. -/
theorem generator_injective :
    Function.Injective (StronglyContinuousSemigroup.generator (X := X)) :=
  fun _ _ h => eq_of_generator_eq h

end StronglyContinuousSemigroup

/-- Two contraction semigroups with the same generator are equal. -/
theorem ContractionSemigroup.eq_of_generator_eq {S T : ContractionSemigroup X}
    (hgen : S.toStronglyContinuousSemigroup.generator
      = T.toStronglyContinuousSemigroup.generator) :
    S = T := by
  have h := StronglyContinuousSemigroup.eq_of_generator_eq hgen
  refine ContractionSemigroup.ext fun τ => ?_
  rw [← S.toStronglyContinuousSemigroup_apply, ← T.toStronglyContinuousSemigroup_apply, h]

end TauCeti.Semigroups

end
